name: VLP
type: S2T
data:
  train_label_path: /path/to/datastet/PHOENIX-2014-T/features/features.train
  dev_label_path: /path/to/datastet/PHOENIX-2014-T/features/features.dev
  test_label_path: /path/to/datastet/PHOENIX-2014-T/features/features.test
  img_path: /path/to/datastet/PHOENIX-2014-T/features/fullFrame-210x260px/
  max_length: 300
  replace: 0
testing:
  translation_max_output_length: 30
training:
  wandb: disabled # online or disabled
  mix_radio: 
  - 0
  - 0
  loss_weight:
  - 0
  - 1
  gloss_free: 0
  stride: 1
  frame_length: 4
  temporal_arg: false
  accumulation: 1
  optimizer: Adam
  freeze: False
  learning_rate: 1.0e-05
  vl_learning_rate: 1.0e-03
  betas:
  - 0.9
  - 0.98
  scheduling: cosin
  learning_rate_min: 1.0e-08
  weight_decay: 0.0
  patience: 8
  eps: 1.0e-09
  scale_embedding: False
model:
  transformer:  ./pretrain_models/MBart_proun
  visual_encoder: ./pretrain_models/mytran